name: EPG

on:
  schedule:
    - cron: '40 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo sed -i 's|http://.*.ubuntu.com|http://archive.ubuntu.com|g' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y jq curl libxml2-utils

      - name: Download files from files.json
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          mkdir -p epg
          cat files.json | jq -r 'to_entries[] | "\(.key) \(.value)"' | while read -r filename urls; do
            echo "处理文件: $filename"
            xml_file="epg/$filename"
            xml_file_tmp="$xml_file.tmp"
            success=false

            IFS=',' read -ra URL_LIST <<< "$urls"
            for url in "${URL_LIST[@]}"; do
              url_trimmed=$(echo "$url" | xargs)  # 去除前后空格
              echo "尝试下载: $url_trimmed"
              if [[ "$url_trimmed" == "https://assets.livednow.com/epg.xml" ]]; then
                curl --retry 5 -x "$PROXY_URL" -o "$xml_file_tmp" "$url_trimmed" || continue
              else
                curl --retry 5 -o "$xml_file_tmp" "$url_trimmed" || continue
              fi

              if grep -iq "404 Not Found" "$xml_file_tmp"; then
                echo "下载内容包含404错误，继续尝试下一个URL"
                continue
              fi

              if xmllint --noout "$xml_file_tmp"; then
                mv "$xml_file_tmp" "$xml_file"
                gzip -kf "$xml_file"
                success=true
                echo "成功下载并验证: $filename"
                break
              else
                echo "无效的XML文件: $filename，尝试下一个URL"
              fi
            done

            rm -f "$xml_file_tmp"
            if [ "$success" = false ]; then
              echo "所有URL均尝试失败：$filename"
            fi
          done

          cat files.json | jq -r 'keys[]' | while read -r filename; do
            echo "FILENAME_$filename=epg/$filename" >> $GITHUB_ENV
            echo "FILENAME_${filename%.xml}.gz=epg/${filename%.xml}.gz" >> $GITHUB_ENV
          done

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add epg/*
          if ! git diff --cached --quiet; then
            now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
            git commit -m "更新时间：$now_time"
            git push origin main || echo "推送到GitHub失败"
          else
            echo "没有文件可提交"
          fi

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: taksssss/tv
          event-type: sync
