name: EPG

on:
  schedule:
    - cron: '40 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq (for parsing JSON)
        run: sudo apt-get install -y jq

      - name: Download files from files.json
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          sudo sed -i 's|http://.*.ubuntu.com|http://archive.ubuntu.com|g' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          mkdir -p epg
          
          cat files.json | jq -r 'to_entries[] | "\(.key) \(.value)"' | while IFS= read -r line; do
            filename=$(echo "$line" | awk '{print $1}')
            urls=$(echo "$line" | cut -d' ' -f2- | tr ',' '\n' | sed 's/^[ \t]*//;s/[ \t]*$//')
            xml_file="epg/$filename"
            xml_file_tmp="$xml_file.tmp"
            success=0

            for url in $urls; do
              echo "尝试下载 $filename 从 $url"
              if [[ "$url" == "https://assets.livednow.com/epg.xml" ]]; then
                curl --retry 5 -x "$PROXY_URL" -o "$xml_file_tmp" "$url" || continue
              else
                curl --retry 5 -o "$xml_file_tmp" "$url" || continue
              fi

              if grep -iq "404 Not Found" "$xml_file_tmp"; then
                echo "$url 返回了 404 错误，尝试下一个"
                continue
              fi

              if xmllint --noout "$xml_file_tmp"; then
                echo "成功下载并验证 XML：$filename"
                mv "$xml_file_tmp" "$xml_file"
                gzip -kf "$xml_file"
                success=1
                break
              else
                echo "无效的 XML 文件：$filename，尝试下一个"
              fi
            done

            [ $success -eq 0 ] && echo "$filename 所有URL均失败"
            rm -f "$xml_file_tmp"
          done
          
          cat files.json | jq -r 'keys[]' | while read -r filename; do
            echo "FILENAME_$filename=epg/$filename" >> $GITHUB_ENV
            echo "FILENAME_${filename%.xml}.gz=epg/${filename%.xml}.gz" >> $GITHUB_ENV
          done

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add epg/*
          if ! git diff --cached --quiet; then
            now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
            git commit -m "更新时间：$now_time"
            git push origin main || echo "推送到GitHub失败"
          else
            echo "没有文件可提交"
          fi
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: taksssss/tv
          event-type: sync
